#8 [REFACTOR] Rename role using underscore
idealista/opengrok-role pull request #11
Opened 2020-12-30 10:38 UTC by emepege

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

### Benefits

#8 

### Possible Drawbacks

None

### Applicable Issues

resolve #8

2020-12-30 11:17 UTC, vicsufer requested changes

2020-12-30 11:17 UTC, vicsufer commented on README.md
> +[![Build Status](https://travis-ci.org/idealista/opengrok_role.png)](https://travis-ci.org/idealista/opengrok_role)
Now we're using travis-ci.com.

travis-ci.org/* is just redirecting to travis-ci.com/*

2020-12-30 11:53 UTC, vicsufer approved these changes

2020-12-30 12:20 UTC, xtianae7 approved these changes

2021-01-07 09:37 UTC, caldito approved these changes

2021-01-07 09:37 UTC, dortegau approved these changes

2021-01-07 09:38 UTC, jperera approved these changes

2021-01-07 10:04 UTC, merged